/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AcessoPendenteRouteImport } from './routes/acesso-pendente'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CrmRouteRouteImport } from './routes/crm/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmAprovacoesRouteImport } from './routes/crm/aprovacoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoPendenteRoute = AcessoPendenteRouteImport.update({
  id: '/acesso-pendente',
  path: '/acesso-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRouteRoute = CrmRouteRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRouteRoute,
} as any)
const CrmAprovacoesRoute = CrmAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => CrmRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/acesso': typeof AcessoRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/cadastro': typeof CadastroRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/crm/aprovacoes': typeof CrmAprovacoesRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acesso': typeof AcessoRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/cadastro': typeof CadastroRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/crm/aprovacoes': typeof CrmAprovacoesRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/acesso': typeof AcessoRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/cadastro': typeof CadastroRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/crm/aprovacoes': typeof CrmAprovacoesRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/about'
    | '/acesso'
    | '/acesso-pendente'
    | '/cadastro'
    | '/inicio'
    | '/login'
    | '/crm/aprovacoes'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acesso'
    | '/acesso-pendente'
    | '/cadastro'
    | '/inicio'
    | '/login'
    | '/crm/aprovacoes'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/about'
    | '/acesso'
    | '/acesso-pendente'
    | '/cadastro'
    | '/inicio'
    | '/login'
    | '/crm/aprovacoes'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRouteRoute: typeof CrmRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcessoRoute: typeof AcessoRoute
  AcessoPendenteRoute: typeof AcessoPendenteRoute
  CadastroRoute: typeof CadastroRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-pendente': {
      id: '/acesso-pendente'
      path: '/acesso-pendente'
      fullPath: '/acesso-pendente'
      preLoaderRoute: typeof AcessoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRouteRoute
    }
    '/crm/aprovacoes': {
      id: '/crm/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/crm/aprovacoes'
      preLoaderRoute: typeof CrmAprovacoesRouteImport
      parentRoute: typeof CrmRouteRoute
    }
  }
}

interface CrmRouteRouteChildren {
  CrmAprovacoesRoute: typeof CrmAprovacoesRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteRouteChildren: CrmRouteRouteChildren = {
  CrmAprovacoesRoute: CrmAprovacoesRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteRouteWithChildren = CrmRouteRoute._addFileChildren(
  CrmRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRouteRoute: CrmRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcessoRoute: AcessoRoute,
  AcessoPendenteRoute: AcessoPendenteRoute,
  CadastroRoute: CadastroRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
